version: 0.0
os: linux

files:
  - source: target/manageemployee-0.0.1.jar
    destination: /opt/tomcat/webapps/
permissions:
  - object: setup.sh  # Apply permissions to the setup.sh script
    mode: 777  # Make it executable
    owner: root
    type:
      - file
hooks:
  ApplicationStart:
    - location: setup.sh
      timeout: 300
      runas: root
      
