version: 0.0
os: linux

files:
  - source: setup.sh
    destination: /opt/tomcat/webapps/
  - source: target/manageemployee-0.0.1.jar
    destination: /opt/tomcat/webapps/

hooks:
  AfterInstall:
    - location: chmod +x /opt/tomcat/webapps/setup.sh
      timeout: 60
      runas: root
    - location: /opt/tomcat/webapps/setup.sh  # Use full path to setup.sh
      timeout: 300
      runas: root
      
