version: 0.2

phases:

  install:

    runtime-versions:

      java: corretto11  # Specify the Java version (e.g., Corretto 11 or OpenJDK 11)

  pre_build:

    commands:

      - echo "Setting up environment..."

      - mkdir libs

      - echo "Downloading dependencies from S3..."

      - aws s3 cp s3://sagar-artifact/Email-service/target/emailservice-0.0.1.jar libs/

      - aws s3 cp s3://sagar-artifact/Manage-Model/target/managemodel-0.0.1.jar libs/

      - aws s3 cp s3://sagar-artifact/Auth/target/authToken-2.0.0.jar libs/

  build:

    commands:

      - echo "Building the project..."

      - mvn clean package spring-boot:repackage

      - echo "Extracting the generated JAR..."

      - mkdir unpacked-jar

      - cd unpacked-jar

      - jar -xvf ../target/manageemployee-0.0.1.jar

      - echo "Copying dependencies into the extracted JAR structure..."

      - mkdir -p BOOT-INF/lib

      - cp ../libs/*.jar BOOT-INF/lib/

      - echo "Repackaging the JAR with additional dependencies..."

      - jar -cvf ../target/manageemployee-0.0.1-final.jar *

      - cd ..

      - echo "Extracting the newly created JAR file to verify dependencies..."

      - mkdir final-unpacked-jar

      - cd final-unpacked-jar

      - jar -xvf ../target/manageemployee-0.0.1-final.jar

      - echo "Listing all JAR files in the 'libs' folder of the newly created JAR..."

      - ls -lha BOOT-INF/lib
 
      - echo "Repackaging the JAR after final extraction..."

      - jar -cvf ../target/manageemployee-0.0.1-final-final.jar *
 
  post_build:

    commands:

      - echo "Build and verification complete!"

      - echo "Final artifacts in the target folder:"

      - ls -hla target/

artifacts:

  files:

    - target/*.jar  # Include the final repackaged JAR

    - setup.sh

    - appspec.yml

 
