version: 0.2

phases:

  install:

    runtime-versions:

      java: corretto11  # Specify the Java version (e.g., Corretto 11 or OpenJDK 11)

  pre_build:

    commands:

      - echo "Setting up environment..."

      - mkdir libs

      - echo "Downloading dependencies from S3..."

      - aws s3 cp s3://sagar-artifact/Email-service/target/emailservice-0.0.1.jar libs/

      - aws s3 cp s3://sagar-artifact/Manage-Model/target/managemodel-0.0.1.jar libs/

      - aws s3 cp s3://sagar-artifact/Auth/target/authToken-2.0.0.jar libs/

  build:

    commands:

      - echo "Building the project..."
      - cd /root/.m2/repository/
      - mvn install:install-file -Dfile=libs/emailservice-0.0.1.jar -DgroupId=sendemail -DartifactId=emailservice -Dversion=0.0.1 -Dpackaging=jar
      - mvn install:install-file -Dfile=libs/managemodel-0.0.1.jar -DgroupId=managemodel -DartifactId=managemodel -Dversion=0.0.1 -Dpackaging=jar
      - mvn install:install-file -Dfile=libs/authToken-2.0.0.jar -DgroupId=authToken -DartifactId=authToken -Dversion=2.0.0 -Dpackaging=jar
      - cd ${CODEBUILD_SRC_DIR}
      - mvn clean package spring-boot:repackage

  post_build:

    commands:

      - echo "Build and verification complete!"

      - echo "Final artifacts in the target folder:"

      - ls -hla target/

artifacts:

  files:

    - target/*.jar  # Include the final repackaged JAR

    - setup.sh

    - appspec.yml

 
