version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8         
    commands:
      - echo "Installing dependencies..."
      - mvn --version  
      - java -version   
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package spring-boot:repackage
artifacts:
  files: 
    - target/datareporting-0.0.1.jar
    - target/appspec.yml
    - setup.sh
  discard-paths: yes